# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: openhealthhub.org
canonical: https://fhir.openhealthhub.org
version: 0.0.1-current
name: openhealthhub
title: "Openhealthhub"
description: Openhealthhub
releaseLabel: ci-build
#releaseLabel: ballot
#releaseLabel: trial-use
#releaseLabel: release
#date: 2022-01-02
status: draft
publisher:
  ## Find your domain contact on the https://www.ihe.net/ihe_domains page
  - name: Openhealthhub.org
  - url: https://openhealthhub.org/
  - email: mayfield.g.kev@gmail.com
contact:
  - name: Openhealthhub.org
    telecom:
      - system: email
        value: mayfield.g.kev@gmail.com
license:  CC-BY-4.0
fhirVersion: 4.0.1
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2025+
dependencies:
  fhir.r4.ukcore.stu3.currentbuild:
    version: 0.0.19-pre-release
    uri: https://simplifier.net/guide/ukcoreversionhistory


parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
# valueSets and codeSystems should be given OIDs, this is especially required if that codeSystem or valueSet is going to be used by CDA. IHE has an OID root that is managed https://wiki.ihe.net/index.php/OID_Registration, with a branch assigned to each IHE domain. Each IHE domain should have a page where they manage assignments within their branch. an OID should be assigned to each IG, and that OID placed below so that the IG publisher will manage OID assignment to all valueSets and codeSystems defined in that IG. The IG publisher will create an ./oids.ini in the project root that will need to be checked into your github repository.
#  auto-oid-root: 1.3.6.1.4.1.19376.1.5....

#resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true


pages:
# itemize here each narrative page. Include assigned section numbers when appropriate. The order they appear here is the order they will appear in the TOC and on the next/prev navigation.
  index.md:
    title: Home
    generation: markdown
  volume-0.md:
    title: Clinical Pathways (Volume 0)
    generation: markdown
  volume-2.md:
    title: Interfaces (Volume 2)
    generation: markdown
  volume-3.md:
    title: Clinical Documents (Volume 3)
    generation: markdown
  terminology.md:
    title: Terminology
    generation: markdown
menu:
  Home: index.html
  Clinical Pathway (Volume 0): volume-0.html
  Interfaces (Volume 2): volume-2.html
  Clinical Documents (Volume 3): volume-3.html
  Terminology: terminology.html
